# Default values for sink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: [{ name: acrcred }]

image:
  pceilocapirepo: pceiregistry.azurecr.io/lorareadserver
  pceilocapitag: latest 
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
#serivce port value for sink service
  type: NodePort
  ports:
    port: 50005
    nodePort: 30808
